import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from 'next/script';

export const metadata: Metadata = {
  title: "Panda Express POS System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />
        <Script id="google-translate-init">
          {`
            function googleTranslateElementInit() {
              new google.translate.TranslateElement(
                { pageLanguage: 'en' },
                'google_translate_element'
              );
            }
          `}
        </Script>
      </head>
      <body className="bg-red-400">
        <div id="google_translate_element" className="fixed top-0 left-0 m-4 z-50"></div>
        {children}
      </body>
    </html>
  );
}






// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";


// export const metadata: Metadata = {
//   title: "Panda Express POS System",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="bg-red-400">
//         {children}
      
        
//       </body>
//     </html>
//   );
// }
